name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "rust" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "rust" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
      working-directory: "rust"
